services:
  db:
    image: postgres:14.7-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rake devops:prepare && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    depends_on:
      - db
      - app-trace
    env_file:
      - ./.env.development
  app-trace:
    image: jaegertracing/all-in-one:1.29
    ports:
      - "16686:16686"
      - "4318:4318"
      - "6831:6831"
  console-dev:
    image: ruby:3.2.2
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: sh
    stdin_open: true
    tty: true
